// GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Run `yarn workspace @onborn/analytics sync-version` after bumping the version.

/** Version of this SDK package, reported with every analytics event. */
export const ONBORN_SDK_VERSION = "0.1.0-beta.3";
