export const PHOSPHOR_ICON_NAMES = [
  "airplane",
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "baby",
  "bank",
  "barbell",
  "bed",
  "bell",
  "bicycle",
  "book",
  "book-open",
  "books",
  "bowl-food",
  "brain",
  "briefcase",
  "buildings",
  "calendar",
  "calendar-check",
  "camera",
  "car",
  "caret-down",
  "caret-left",
  "caret-right",
  "caret-up",
  "chart-bar",
  "chart-line",
  "chart-line-up",
  "chart-pie-slice",
  "chat-circle",
  "chats-circle",
  "check",
  "check-circle",
  "clipboard-text",
  "clock",
  "cloud-moon",
  "coffee",
  "confetti",
  "copy",
  "credit-card",
  "crown",
  "currency-dollar",
  "download-simple",
  "envelope-simple",
  "eye",
  "eye-slash",
  "fire",
  "flower",
  "fork-knife",
  "game-controller",
  "gift",
  "globe",
  "graduation-cap",
  "heart",
  "heartbeat",
  "headphones",
  "hourglass",
  "house",
  "image",
  "images",
  "info",
  "key",
  "leaf",
  "lightbulb",
  "lightning",
  "link",
  "list-checks",
  "lock",
  "magic-wand",
  "magnifying-glass",
  "map-pin",
  "medal",
  "medal-military",
  "microphone",
  "minus",
  "money",
  "moon",
  "mountains",
  "music-notes",
  "notepad",
  "paint-brush",
  "paint-bucket",
  "palette",
  "pencil-simple",
  "pen-nib",
  "person-simple-run",
  "person-simple-walk",
  "phone",
  "piggy-bank",
  "planet",
  "plus",
  "pulse",
  "question",
  "question-mark",
  "receipt",
  "rocket",
  "share-network",
  "shield-check",
  "shopping-cart",
  "smiley",
  "sneaker-move",
  "sparkle",
  "star",
  "sun",
  "target",
  "timer",
  "train",
  "trash",
  "trend-down",
  "trend-up",
  "trophy",
  "upload-simple",
  "user",
  "user-circle",
  "users",
  "video-camera",
  "wallet",
  "warning",
  "x",
  "x-circle",
] as const;

export type PhosphorIconNameValue = (typeof PHOSPHOR_ICON_NAMES)[number];

export const PHOSPHOR_ICON_LABELS: Record<PhosphorIconNameValue, string> =
  Object.fromEntries(
    PHOSPHOR_ICON_NAMES.map((name) => [
      name,
      name
        .split("-")
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(" "),
    ]),
  ) as Record<PhosphorIconNameValue, string>;

export const PHOSPHOR_ICON_SELECT_OPTIONS = PHOSPHOR_ICON_NAMES.map(
  (name) => ({
    value: name,
    label: PHOSPHOR_ICON_LABELS[name],
  }),
);
