import {
  ArrowLeft,
  ArrowRight,
  Bell,
  Calendar,
  CaretLeft,
  Check,
  CheckCircle,
  Crown,
  Fire,
  Gift,
  Heart,
  Lightning,
  Lock,
  MagicWand,
  Rocket,
  ShieldCheck,
  Sparkle,
  Star,
  Target,
  Trophy,
  User,
  X,
  type Icon,
} from "phosphor-react-native";
import type { PhosphorIconName } from "@onborn/sdk-contracts";

export const PHOSPHOR_ICONS: Record<PhosphorIconName, Icon> = {
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  bell: Bell,
  calendar: Calendar,
  "caret-left": CaretLeft,
  check: Check,
  "check-circle": CheckCircle,
  crown: Crown,
  fire: Fire,
  gift: Gift,
  heart: Heart,
  lightning: Lightning,
  lock: Lock,
  "magic-wand": MagicWand,
  rocket: Rocket,
  "shield-check": ShieldCheck,
  sparkle: Sparkle,
  star: Star,
  target: Target,
  trophy: Trophy,
  user: User,
  x: X,
};
