import {
  Airplane,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Baby,
  Bank,
  Barbell,
  Bed,
  Bell,
  Bicycle,
  Book,
  BookOpen,
  Books,
  BowlFood,
  Brain,
  Briefcase,
  Buildings,
  Calendar,
  CalendarCheck,
  Camera,
  Car,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  ChartLine,
  ChartLineUp,
  ChartPieSlice,
  ChatCircle,
  ChatsCircle,
  Check,
  CheckCircle,
  ClipboardText,
  Clock,
  CloudMoon,
  Coffee,
  Confetti,
  Copy,
  CreditCard,
  Crown,
  CurrencyDollar,
  DownloadSimple,
  EnvelopeSimple,
  Eye,
  EyeSlash,
  Fire,
  Flower,
  ForkKnife,
  GameController,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  Heartbeat,
  Headphones,
  Hourglass,
  House,
  Image,
  Images,
  Info,
  Key,
  Leaf,
  Lightbulb,
  Lightning,
  Link,
  ListChecks,
  Lock,
  MagicWand,
  MagnifyingGlass,
  MapPin,
  Medal,
  MedalMilitary,
  Microphone,
  Minus,
  Money,
  Moon,
  Mountains,
  MusicNotes,
  Notepad,
  PaintBrush,
  PaintBucket,
  Palette,
  PencilSimple,
  PenNib,
  PersonSimpleRun,
  PersonSimpleWalk,
  Phone,
  PiggyBank,
  Planet,
  Plus,
  Pulse,
  Question,
  QuestionMark,
  Receipt,
  Rocket,
  ShareNetwork,
  ShieldCheck,
  ShoppingCart,
  Smiley,
  SneakerMove,
  Sparkle,
  Star,
  Sun,
  Target,
  Timer,
  Train,
  Trash,
  TrendDown,
  TrendUp,
  Trophy,
  UploadSimple,
  User,
  UserCircle,
  Users,
  VideoCamera,
  Wallet,
  Warning,
  X,
  XCircle,
  type Icon,
} from "phosphor-react-native";
import type { PhosphorIconName } from "@onborn/sdk-contracts";

export const PHOSPHOR_ICONS: Record<PhosphorIconName, Icon> = {
  airplane: Airplane,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  baby: Baby,
  bank: Bank,
  barbell: Barbell,
  bed: Bed,
  bell: Bell,
  bicycle: Bicycle,
  book: Book,
  "book-open": BookOpen,
  books: Books,
  "bowl-food": BowlFood,
  brain: Brain,
  briefcase: Briefcase,
  buildings: Buildings,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  camera: Camera,
  car: Car,
  "caret-down": CaretDown,
  "caret-left": CaretLeft,
  "caret-right": CaretRight,
  "caret-up": CaretUp,
  "chart-bar": ChartBar,
  "chart-line": ChartLine,
  "chart-line-up": ChartLineUp,
  "chart-pie-slice": ChartPieSlice,
  "chat-circle": ChatCircle,
  "chats-circle": ChatsCircle,
  check: Check,
  "check-circle": CheckCircle,
  "clipboard-text": ClipboardText,
  clock: Clock,
  "cloud-moon": CloudMoon,
  coffee: Coffee,
  confetti: Confetti,
  copy: Copy,
  "credit-card": CreditCard,
  crown: Crown,
  "currency-dollar": CurrencyDollar,
  "download-simple": DownloadSimple,
  "envelope-simple": EnvelopeSimple,
  eye: Eye,
  "eye-slash": EyeSlash,
  fire: Fire,
  flower: Flower,
  "fork-knife": ForkKnife,
  "game-controller": GameController,
  gift: Gift,
  globe: Globe,
  "graduation-cap": GraduationCap,
  heart: Heart,
  heartbeat: Heartbeat,
  headphones: Headphones,
  hourglass: Hourglass,
  house: House,
  image: Image,
  images: Images,
  info: Info,
  key: Key,
  leaf: Leaf,
  lightbulb: Lightbulb,
  lightning: Lightning,
  link: Link,
  "list-checks": ListChecks,
  lock: Lock,
  "magic-wand": MagicWand,
  "magnifying-glass": MagnifyingGlass,
  "map-pin": MapPin,
  medal: Medal,
  "medal-military": MedalMilitary,
  microphone: Microphone,
  minus: Minus,
  money: Money,
  moon: Moon,
  mountains: Mountains,
  "music-notes": MusicNotes,
  notepad: Notepad,
  "paint-brush": PaintBrush,
  "paint-bucket": PaintBucket,
  palette: Palette,
  "pencil-simple": PencilSimple,
  "pen-nib": PenNib,
  "person-simple-run": PersonSimpleRun,
  "person-simple-walk": PersonSimpleWalk,
  phone: Phone,
  "piggy-bank": PiggyBank,
  planet: Planet,
  plus: Plus,
  pulse: Pulse,
  question: Question,
  "question-mark": QuestionMark,
  receipt: Receipt,
  rocket: Rocket,
  "share-network": ShareNetwork,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  smiley: Smiley,
  "sneaker-move": SneakerMove,
  sparkle: Sparkle,
  star: Star,
  sun: Sun,
  target: Target,
  timer: Timer,
  train: Train,
  trash: Trash,
  "trend-down": TrendDown,
  "trend-up": TrendUp,
  trophy: Trophy,
  "upload-simple": UploadSimple,
  user: User,
  "user-circle": UserCircle,
  users: Users,
  "video-camera": VideoCamera,
  wallet: Wallet,
  warning: Warning,
  x: X,
  "x-circle": XCircle,
};
