import { WELCOME_LAYOUT_PRESET_VALUES } from "../steps/welcome/types";
import { QUIZ_LAYOUT_PRESET_VALUES } from "../steps/quiz/types";
import { BENEFITS_LAYOUT_PRESET_VALUES } from "../steps/benefits/types";
import { CUSTOM_LAYOUT_PRESET_VALUES } from "../steps/custom/types";
import { LOADING_LAYOUT_PRESET_VALUES } from "../steps/loading/types";
import { METRICS_LAYOUT_PRESET_VALUES } from "../steps/metrics/types";
import { NATIVE_CUSTOM_LAYOUT_PRESET_VALUES } from "../steps/native-custom/types";
import { PERMISSIONS_LAYOUT_PRESET_VALUES } from "../steps/permissions/types";
import { QUIZ_ANSWER_LAYOUT_PRESET_VALUES } from "../steps/quiz-answer/types";
import { SOCIAL_PROOF_LAYOUT_PRESET_VALUES } from "../steps/social-proof/types";
import type { TextFontFamily } from "../primitives";

const ALL_LAYOUT_PRESET_VALUES = [
  "content_focused",
  "hero",
  "hero_sheet",
  "split",
] as const;

export type LayoutSlot = "top" | "hero" | "content" | "bottom";

/**
 * Layout preset ids — same tuple as welcome until other steps define their own lists.
 * Mirrored in zod (`schema.ts`) and RN `Layout`.
 */
export const LAYOUT_PRESET_VALUES = ALL_LAYOUT_PRESET_VALUES;

export type LayoutPreset = (typeof LAYOUT_PRESET_VALUES)[number];

export const LAYOUT_BG_GRADIENT_PRESET_VALUES = [
  "aurora",
  "sunset_glow",
  "ocean_depth",
  "grape_soda",
  "mint_breeze",
  "midnight_pulse",
  "peach_blush",
  "emerald_night",
  "cotton_candy",
  "golden_hour",
  "arctic_blue",
  "berry_fusion",
  "electric_lime",
  "deep_space",
  "rose_quartz",
  "cyber_teal",
  "lava_lamp",
  "fresh_sky",
  "royal_ink",
  "matcha_mist",
  "coral_reef",
  "blueberry_cream",
  "neon_night",
  "soft_lilac",
] as const;

export type LayoutBgGradientPreset =
  (typeof LAYOUT_BG_GRADIENT_PRESET_VALUES)[number];

export type LayoutBgSolid = {
  type: "solid";
  color: string;
};

export type LayoutBgGradientStop = {
  color: string;
  /** 0..1 position along the gradient line. */
  position?: number;
};

export type LayoutBgLinearGradient = {
  type: "linear_gradient";
  /** Named preset (backward compatible). */
  preset?: LayoutBgGradientPreset;
  /** Custom gradient angle in degrees (CSS convention, 0 = to top). */
  angle?: number;
  /** Custom gradient stops (2–4). Wins over `preset` when present. */
  stops?: LayoutBgGradientStop[];
};

export type LayoutBgImage = {
  type: "image";
  /** Runtime URL, usually a short-lived signed URL generated by backend. */
  src?: string;
  /** Stable private storage bucket reference saved in flow config. */
  bucket?: string;
  /** Stable private storage object path saved in flow config. */
  path?: string;
  resizeMode?: "cover" | "contain";
  overlayColor?: string;
  overlayOpacity?: number;
};

export type LayoutBgVideo = {
  type: "video";
  /** Runtime URL, usually a short-lived signed URL generated by backend. */
  src?: string;
  /** Stable private storage bucket reference saved in flow config. */
  bucket?: string;
  /** Stable private storage object path saved in flow config. */
  path?: string;
  resizeMode?: "cover" | "contain";
};

export type LayoutBg =
  | LayoutBgSolid
  | LayoutBgLinearGradient
  | LayoutBgImage
  | LayoutBgVideo;

export const LAYOUT_BG_GRADIENT_PRESETS: Record<
  LayoutBgGradientPreset,
  {
    label: string;
    colors: readonly [string, string];
  }
> = {
  aurora: {
    label: "Aurora",
    colors: ["#101826", "#5F6FFF"],
  },
  sunset_glow: {
    label: "Sunset Glow",
    colors: ["#321A2F", "#FF7A59"],
  },
  ocean_depth: {
    label: "Ocean Depth",
    colors: ["#071E2F", "#15B8A6"],
  },
  grape_soda: {
    label: "Grape Soda",
    colors: ["#22133D", "#B86BFF"],
  },
  mint_breeze: {
    label: "Mint Breeze",
    colors: ["#0F2A24", "#8CE99A"],
  },
  midnight_pulse: {
    label: "Midnight Pulse",
    colors: ["#080B16", "#2F80ED"],
  },
  peach_blush: {
    label: "Peach Blush",
    colors: ["#FFF1EB", "#F97316"],
  },
  emerald_night: {
    label: "Emerald Night",
    colors: ["#052E2B", "#22C55E"],
  },
  cotton_candy: {
    label: "Cotton Candy",
    colors: ["#FDF2F8", "#A78BFA"],
  },
  golden_hour: {
    label: "Golden Hour",
    colors: ["#451A03", "#FACC15"],
  },
  arctic_blue: {
    label: "Arctic Blue",
    colors: ["#EFF6FF", "#38BDF8"],
  },
  berry_fusion: {
    label: "Berry Fusion",
    colors: ["#3B0764", "#EC4899"],
  },
  electric_lime: {
    label: "Electric Lime",
    colors: ["#071B18", "#A3E635"],
  },
  deep_space: {
    label: "Deep Space",
    colors: ["#020617", "#6366F1"],
  },
  rose_quartz: {
    label: "Rose Quartz",
    colors: ["#FFF1F2", "#FB7185"],
  },
  cyber_teal: {
    label: "Cyber Teal",
    colors: ["#042F2E", "#2DD4BF"],
  },
  lava_lamp: {
    label: "Lava Lamp",
    colors: ["#1F0A14", "#F43F5E"],
  },
  fresh_sky: {
    label: "Fresh Sky",
    colors: ["#F0FDFA", "#0EA5E9"],
  },
  royal_ink: {
    label: "Royal Ink",
    colors: ["#111827", "#8B5CF6"],
  },
  matcha_mist: {
    label: "Matcha Mist",
    colors: ["#F7FEE7", "#84CC16"],
  },
  coral_reef: {
    label: "Coral Reef",
    colors: ["#172554", "#FB923C"],
  },
  blueberry_cream: {
    label: "Blueberry Cream",
    colors: ["#EEF2FF", "#2563EB"],
  },
  neon_night: {
    label: "Neon Night",
    colors: ["#030712", "#22D3EE"],
  },
  soft_lilac: {
    label: "Soft Lilac",
    colors: ["#FAF5FF", "#C084FC"],
  },
};

export interface LayoutConfig {
  preset?: LayoutPreset;
  bg?: LayoutBg;
  fontFamily?: TextFontFamily;
  safeArea?: boolean;
}

/** Per-step allowed layout presets; welcome pulls from `WELCOME_LAYOUT_PRESET_VALUES`. */
export const STEP_ALLOWED_LAYOUTS = {
  benefits: BENEFITS_LAYOUT_PRESET_VALUES,
  custom: CUSTOM_LAYOUT_PRESET_VALUES,
  loading: LOADING_LAYOUT_PRESET_VALUES,
  metrics: METRICS_LAYOUT_PRESET_VALUES,
  native_custom: NATIVE_CUSTOM_LAYOUT_PRESET_VALUES,
  permissions: PERMISSIONS_LAYOUT_PRESET_VALUES,
  quiz: QUIZ_LAYOUT_PRESET_VALUES,
  quiz_answer: QUIZ_ANSWER_LAYOUT_PRESET_VALUES,
  social_proof: SOCIAL_PROOF_LAYOUT_PRESET_VALUES,
  welcome: WELCOME_LAYOUT_PRESET_VALUES,
} as const;

export type StepAllowedLayoutsKey = keyof typeof STEP_ALLOWED_LAYOUTS;

/** Step keys that have layout preset rules (grows with new step contracts). */
export type ScreenType = StepAllowedLayoutsKey;
