/**
 * Regenerate `src/version.ts` from package.json.
 *
 * The SDK reports its own version in analytics, so that value must never be
 * hand-maintained (it silently drifts and poisons telemetry). Importing
 * package.json at runtime is not safe across every RN/Metro/bundler setup, so
 * the version is baked into a generated constant instead, and this script is
 * wired into `prepack` so publishing cannot ship a stale one.
 *
 * Run `node scripts/sync-version.mjs --check` in CI to fail on drift.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(
  readFileSync(join(root, "package.json"), "utf8"),
);
const target = join(root, "src", "version.ts");

const contents = `// GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Run \`yarn workspace @onborn/analytics sync-version\` after bumping the version.

/** Version of this SDK package, reported with every analytics event. */
export const ONBORN_SDK_VERSION = "${version}";
`;

if (process.argv.includes("--check")) {
  const current = readFileSync(target, "utf8");
  if (current !== contents) {
    console.error(
      `src/version.ts is out of sync with package.json (${version}). Run: yarn workspace @onborn/analytics sync-version`,
    );
    process.exit(1);
  }
  console.log(`src/version.ts matches package.json (${version}).`);
  process.exit(0);
}

writeFileSync(target, contents);
console.log(`src/version.ts set to ${version}`);
